Issue #4. Remove notifications from OS tray when they are read in the Inbox page of CM.
TransformativeMed/cordova-plugin-push pull request #9
Opened 2023-08-07 19:00 UTC by Jacob-Cuevas

IMPORTANT: This PR should be merged once the PR #8 is approved.

## Description

This PR adds the following changes:
- Adds a new method that will be used to remove notifications from the OS tray by a `notID` or remove the notification grouper that was manually created.
- Reverts changes of the `clearNotification` method since it is used to remove all notifications from the OS tray, including the badge number displayed in the app icon.

## Related Issue

https://github.com/TransformativeMed/cordova-plugin-push/issues/4

## Motivation and Context

This method was created as part of the solution for issue #3 , since there must be a way to remove the notification grouper from the OS tray.

## How Has This Been Tested?

These changes were testing in a mobile device with the following specs:
- `16.5.1` iOS version.
- iPhone XR model.

## Screenshots (if appropriate):

- Remove a single notification from the OS tray when the user opens the reminder that was created using its data.

https://github.com/TransformativeMed/cordova-plugin-push/assets/12654157/c08a2324-f45a-49db-9a6e-a6fa4f0d5f71

- Remove the notification grouper from the OS tray when the reminder that was created from a single notification is opened.

https://github.com/TransformativeMed/cordova-plugin-push/assets/12654157/52ec3281-7637-4794-aee9-1a53534838b9

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-08-07 23:48 UTC, ElliotNB requested changes
Can we chat tomorrow around 12PM Pacific about the approach here? I'm hoping that we can keep CORES Mobile logic out of the plugin component itself. But I need to understand 1. if that's possible and 2. if it's going to add to the complexity.

2023-08-07 23:48 UTC, ElliotNB commented on src/ios/AppDelegate+notification.m
> +    if ( [userInfo objectForKey:@"coresPayload"] ) {
Ditto from my other code review in pull request #8

2023-08-07 23:48 UTC, ElliotNB commented on src/ios/AppDelegate+notification.m
> +                if ([userInfo objectForKey:@"coresPayload"]) {
Ditto

2023-08-08 23:07 UTC, Jacob-Cuevas commented
Closing this PR since the PR #10 will move these changes to the `master` branch. Also, I had a conversation with Elliot about these changes and for now those will be introduced as they are in the branch.

2023-08-08 23:07 UTC, closed without merging